/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'hufenchi' 
 * Target:  'hufenchi' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* MDK-Packs::Data Exchange:JSON:cJSON@1.7.7 */
#define RTE_DataExchange_JSON_cJSON     /* cJSON */


#endif /* RTE_COMPONENTS_H */
